language: ruby
cache: bundler
bundler_args: --without development
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake refinery:testing:dummy_app"
script:
  - "DISPLAY=:99.0 bundle exec rspec spec"
env:
  - DB=postgresql
  - DB=mysql
notifications:
  email: true
  irc:
    use_notice: true
    skip_join: true
    channels:
      - "irc.freenode.org#refinerycms"
  webhooks:
    - https://webhooks.gitter.im/e/b5d48907cdc89864b874
rvm:
  - 2.5.0
  - 2.4.3
  - 2.3.6
  - 2.2.9
sudo: false
